//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBillStatus_Billing
    {
        public int TranNO { get; set; }
        public string Studentid { get; set; }
        public string AccountHeading { get; set; }
        public string BillMonths { get; set; }
        public Nullable<decimal> BillDue { get; set; }
        public Nullable<decimal> PaidBill { get; set; }
        public string Class_Stu { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
