//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountprepare
    {
        public Nullable<System.DateTime> Datetimefiled { get; set; }
        public string Assountcode { get; set; }
        public string Accountheading { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expenditure { get; set; }
        public Nullable<decimal> Assets { get; set; }
        public Nullable<decimal> liabilites { get; set; }
        public int TranNo { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
