//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionTable
    {
        public string AdmissionID { get; set; }
        public string StudentName { get; set; }
        public Nullable<decimal> Fees { get; set; }
    }
}
