//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advanceresultmidterm
    {
        public int Tranno { get; set; }
        public string Subject { get; set; }
        public Nullable<decimal> Fullmarks { get; set; }
        public Nullable<decimal> Passmarks { get; set; }
        public Nullable<decimal> Term1 { get; set; }
        public Nullable<decimal> Parti1 { get; set; }
        public string remarks1 { get; set; }
        public Nullable<decimal> Term2 { get; set; }
        public Nullable<decimal> Parti2 { get; set; }
        public string remarks2 { get; set; }
        public Nullable<decimal> Term3 { get; set; }
        public Nullable<decimal> Parti3 { get; set; }
        public string remarks3 { get; set; }
        public Nullable<decimal> Term4 { get; set; }
        public Nullable<decimal> Parti4 { get; set; }
        public string remarks4 { get; set; }
        public Nullable<decimal> Terms5 { get; set; }
        public Nullable<decimal> Parti5 { get; set; }
        public string remarks5 { get; set; }
        public Nullable<decimal> Term6 { get; set; }
        public Nullable<decimal> Parti6 { get; set; }
        public string remarks6 { get; set; }
        public Nullable<decimal> Term7 { get; set; }
        public Nullable<decimal> Parti7 { get; set; }
        public string remarks7 { get; set; }
        public Nullable<decimal> Term8 { get; set; }
        public Nullable<decimal> Parti8 { get; set; }
        public string remarks8 { get; set; }
        public Nullable<decimal> Term9 { get; set; }
        public Nullable<decimal> Parti9 { get; set; }
        public string remarks9 { get; set; }
    }
}
