//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnualLeaveStaff
    {
        public string StaffId { get; set; }
        public Nullable<decimal> H1 { get; set; }
        public Nullable<decimal> H2 { get; set; }
        public Nullable<decimal> H3 { get; set; }
        public Nullable<decimal> H4 { get; set; }
        public Nullable<decimal> H5 { get; set; }
    }
}
