//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Transction_Detail
    {
        public string Miti { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public string Bank_Name { get; set; }
        public string cheque_N0 { get; set; }
        public Nullable<decimal> PreAmount_Balance { get; set; }
        public Nullable<decimal> Deposite { get; set; }
        public Nullable<decimal> WithDraw { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public string Trans_By { get; set; }
        public string CurrentUser { get; set; }
        public int TransNo { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
