//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillExtraIndivusal
    {
        public int tranNo { get; set; }
        public Nullable<System.DateTime> Englis_date { get; set; }
        public string Nepalidate { get; set; }
        public Nullable<int> studentid { get; set; }
        public string billHeading { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string accountCode { get; set; }
        public string Accountheading { get; set; }
        public string Groupheading { get; set; }
        public string billMonthNepali { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
