//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booksstoksview
    {
        public int autoid { get; set; }
        public string SpecialCode { get; set; }
        public Nullable<int> NBooks { get; set; }
        public Nullable<decimal> Lastamount { get; set; }
        public Nullable<decimal> Toatlamount { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
