//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashIn_Out
    {
        public Nullable<System.DateTime> DateValue { get; set; }
        public Nullable<System.DateTime> transctionTime { get; set; }
        public int Total_Trans_Today { get; set; }
        public string AccountHeading { get; set; }
        public Nullable<decimal> PreBalance { get; set; }
        public Nullable<decimal> CashIn { get; set; }
        public Nullable<decimal> CahOut { get; set; }
        public Nullable<decimal> BalanceCash { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TrackId { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
