//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControllIdm
    {
        public int TranNo { get; set; }
        public string FormId { get; set; }
        public string GroupId { get; set; }
        public string ValueGet { get; set; }
    }
}
