//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customercashtable
    {
        public string studentid { get; set; }
        public Nullable<System.DateTime> Datevalue { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public string SelectMonths { get; set; }
        public int TranNo { get; set; }
        public string Columntrack_1 { get; set; }
        public string Columntrack_2 { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
