//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountPurchaseBill
    {
        public int TranNo { get; set; }
        public string SupplerId { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public Nullable<System.DateTime> DateValue { get; set; }
        public string NepaDate { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> DiscountBill { get; set; }
        public Nullable<decimal> BeforeTax { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> AfterDiscount { get; set; }
        public Nullable<decimal> PreBalanceAmount { get; set; }
        public Nullable<decimal> NewBalancecustomer { get; set; }
    }
}
