//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarlySalaryRpto
    {
        public System.DateTime Datevalue { get; set; }
        public string Staffid { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<decimal> Security_staff { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> FinalSalary { get; set; }
    }
}
