//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTerm
    {
        public int Tranno { get; set; }
        public string ExamTerm1 { get; set; }
        public string merseterms { get; set; }
        public string Newtermsname { get; set; }
        public string Yearvalue { get; set; }
        public Nullable<int> valueterms { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
