//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feeStructure_Table
    {
        public int FeeCode { get; set; }
        public string AccountHeading { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Class_Stu { get; set; }
        public string AcademicYear { get; set; }
        public string AccountCode { get; set; }
        public string AccountGroup { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
