//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTransctionTable
    {
        public Nullable<System.DateTime> Datefield { get; set; }
        public Nullable<System.DateTime> Timefield { get; set; }
        public string StudentId { get; set; }
        public string Namefield { get; set; }
        public string Class { get; set; }
        public string Roll { get; set; }
        public string Sectionfield { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> SpecialDiscount { get; set; }
        public string ReservedCast { get; set; }
        public string AccountHead1 { get; set; }
        public string AccountHead2 { get; set; }
        public string AccountHead3 { get; set; }
        public string AccountHead4 { get; set; }
        public string AccountHead5 { get; set; }
        public string AccountHead6 { get; set; }
        public string AccountHead7 { get; set; }
        public string AccountHead8 { get; set; }
        public string AccountHead9 { get; set; }
        public string AccountHead10 { get; set; }
        public string AccountHead11 { get; set; }
        public string AccountHead12 { get; set; }
        public string AccountHead13 { get; set; }
        public string AccountHead14 { get; set; }
        public string AccountHead15 { get; set; }
        public string AccountHead16 { get; set; }
        public string AccountHead17 { get; set; }
        public string AccountHead18 { get; set; }
        public string AccountHead19 { get; set; }
        public string AccountHead20 { get; set; }
        public string OtherAccount1 { get; set; }
        public string OtherAccount2 { get; set; }
        public Nullable<decimal> Headprice1 { get; set; }
        public Nullable<decimal> Headprice2 { get; set; }
        public Nullable<decimal> Headprice3 { get; set; }
        public Nullable<decimal> Headprice4 { get; set; }
        public Nullable<decimal> Headprice5 { get; set; }
        public Nullable<decimal> Headprice6 { get; set; }
        public Nullable<decimal> Headprice7 { get; set; }
        public Nullable<decimal> Headprice8 { get; set; }
        public Nullable<decimal> Headprice9 { get; set; }
        public Nullable<decimal> Headprice10 { get; set; }
        public Nullable<decimal> Headprice11 { get; set; }
        public Nullable<decimal> Headprice12 { get; set; }
        public Nullable<decimal> Headprice13 { get; set; }
        public Nullable<decimal> Headprice14 { get; set; }
        public Nullable<decimal> Headprice15 { get; set; }
        public Nullable<decimal> Headprice16 { get; set; }
        public Nullable<decimal> Headprice17 { get; set; }
        public Nullable<decimal> Headprice18 { get; set; }
        public Nullable<decimal> Headprice19 { get; set; }
        public Nullable<decimal> Headprice20 { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> OtherHeadAmount1 { get; set; }
        public Nullable<decimal> OtherHeadAmount2 { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> BeforeTax { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
        public Nullable<decimal> BalancePayment { get; set; }
        public string CurrentUser { get; set; }
        public string SelectMonths { get; set; }
        public int Transno { get; set; }
    }
}
