//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuebooksrecord
    {
        public int trans { get; set; }
        public string StudentID { get; set; }
        public string Namefield { get; set; }
        public string class_Student { get; set; }
        public string Roll { get; set; }
        public string Telephone { get; set; }
        public string Bookscode { get; set; }
        public string title { get; set; }
        public Nullable<int> Bookstaken { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
