//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeftSchool
    {
        public Nullable<System.DateTime> TodayDate { get; set; }
        public string StudentId { get; set; }
        public string Name_Student { get; set; }
        public string Class_Left { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public Nullable<decimal> BooksLeft { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public string Enrollment_Batch { get; set; }
        public string Left_batch { get; set; }
        public string SchoolView_Coments { get; set; }
        public string ParentView_Coments { get; set; }
        public string WithdrawnBy { get; set; }
        public string Name_WithDrawn { get; set; }
        public string School_Remarks { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
