//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MidfirsttermOnlineView
    {
        public string StudentId { get; set; }
        public string Namefield { get; set; }
        public string Class_stu { get; set; }
        public string Roll { get; set; }
        public string Sectionfield { get; set; }
        public string Subject1 { get; set; }
        public string Subject2 { get; set; }
        public string Subject3 { get; set; }
        public string Subject4 { get; set; }
        public string Subject5 { get; set; }
        public string Subject6 { get; set; }
        public string Subject7 { get; set; }
        public string Subject8 { get; set; }
        public string Subject9 { get; set; }
        public string Subject10 { get; set; }
        public string Subject11 { get; set; }
        public string Subject12 { get; set; }
        public string Subject13 { get; set; }
        public string Subject14 { get; set; }
        public string Subject15 { get; set; }
        public string Subject16 { get; set; }
        public string Subject17 { get; set; }
        public string Subject18 { get; set; }
        public string Subject19 { get; set; }
        public string Subject20 { get; set; }
        public Nullable<decimal> TotalMarksObtain { get; set; }
        public string pratical1 { get; set; }
        public string pratical2 { get; set; }
        public string pratical3 { get; set; }
        public string pratical4 { get; set; }
        public string pratical5 { get; set; }
        public string pratical6 { get; set; }
        public string pratical7 { get; set; }
        public string pratical8 { get; set; }
        public string pratical9 { get; set; }
        public string pratical10 { get; set; }
        public string pratical11 { get; set; }
        public string pratical12 { get; set; }
        public string pratical13 { get; set; }
        public string pratical14 { get; set; }
        public string pratical15 { get; set; }
        public string pratical16 { get; set; }
        public string pratical17 { get; set; }
        public string pratical18 { get; set; }
        public string pratical19 { get; set; }
        public string pratical20 { get; set; }
        public Nullable<decimal> totalpratical { get; set; }
        public Nullable<decimal> totalobtainmarks1 { get; set; }
        public Nullable<decimal> totalobtainmarks2 { get; set; }
        public Nullable<decimal> totalobtainmarks3 { get; set; }
        public Nullable<decimal> totalobtainmarks4 { get; set; }
        public Nullable<decimal> totalobtainmarks5 { get; set; }
        public Nullable<decimal> totalobtainmarks6 { get; set; }
        public Nullable<decimal> totalobtainmarks7 { get; set; }
        public Nullable<decimal> totalobtainmarks8 { get; set; }
        public Nullable<decimal> totalobtainmarks9 { get; set; }
        public Nullable<decimal> totalobtainmarks10 { get; set; }
        public Nullable<decimal> totalobtainmarks11 { get; set; }
        public Nullable<decimal> totalobtainmarks12 { get; set; }
        public Nullable<decimal> totalobtainmarks13 { get; set; }
        public Nullable<decimal> totalobtainmarks14 { get; set; }
        public Nullable<decimal> totalobtainmarks15 { get; set; }
        public Nullable<decimal> totalobtainmarks16 { get; set; }
        public Nullable<decimal> totalobtainmarks17 { get; set; }
        public Nullable<decimal> totalobtainmarks18 { get; set; }
        public Nullable<decimal> totalobtainmarks19 { get; set; }
        public Nullable<decimal> totalobtainmarks20 { get; set; }
        public Nullable<decimal> tatalobtainmarks { get; set; }
        public Nullable<decimal> TotalWorkingDay { get; set; }
        public Nullable<decimal> totalPresentDay { get; set; }
        public Nullable<decimal> totalAbsentDay { get; set; }
        public string Writting { get; set; }
        public string Speaking { get; set; }
        public string Conduct { get; set; }
        public string Neatness { get; set; }
        public string MusicDance { get; set; }
        public string currentUser { get; set; }
        public string PassFail { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Division { get; set; }
        public string Examterm { get; set; }
        public string Year_B_C { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Col1 { get; set; }
        public string Col2 { get; set; }
        public string Col3 { get; set; }
        public string Col4 { get; set; }
        public string Col5 { get; set; }
        public string Col6 { get; set; }
        public string Col7 { get; set; }
        public string Col8 { get; set; }
        public string Col9 { get; set; }
        public string Col10 { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
