//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyEndDay
    {
        public int Tranno { get; set; }
        public Nullable<int> NumericValue { get; set; }
        public Nullable<System.DateTime> EngDate { get; set; }
        public string NepaDate { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
