//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlystaffsalary
    {
        public string StaffId { get; set; }
        public Nullable<decimal> Salaryhead1 { get; set; }
        public Nullable<decimal> Salaryhead2 { get; set; }
        public Nullable<decimal> Salaryhead3 { get; set; }
        public Nullable<decimal> Salaryhead4 { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
