//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlybillPrintIssue
    {
        public int TranNO { get; set; }
        public string InvoiceNo { get; set; }
        public string NepaliDate { get; set; }
        public Nullable<System.DateTime> dateBill { get; set; }
        public string studentId { get; set; }
        public string accountheading { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string accountcode { get; set; }
        public string groupheading { get; set; }
        public string billmonthlyNepali { get; set; }
        public string Class_student { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
