//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numberofworkingday
    {
        public int Transno { get; set; }
        public string EngMonths { get; set; }
        public Nullable<decimal> Workingdays { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Nepalistart { get; set; }
        public string NepaliEnd { get; set; }
        public string Sal { get; set; }
        public Nullable<decimal> ActualWorkedDays { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
