//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentStaff
    {
        public Nullable<System.DateTime> PayDate { get; set; }
        public string JobCardNo { get; set; }
        public string StaffName { get; set; }
        public string MonthPay { get; set; }
        public Nullable<decimal> PreAmount { get; set; }
        public Nullable<decimal> NowPayment { get; set; }
        public string Heading { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public int TransNo { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
