//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Supplier
    {
        public int PVNo { get; set; }
        public Nullable<System.DateTime> Datefield { get; set; }
        public string SupplierId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string PanVat { get; set; }
        public string TelephoneNo { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string GoodsType { get; set; }
        public Nullable<decimal> PreviousAmount { get; set; }
        public Nullable<decimal> todayPayment { get; set; }
        public Nullable<decimal> BalanceAmont { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
