//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSupplier
    {
        public int TranNo { get; set; }
        public string PaymentVoucherNo { get; set; }
        public Nullable<System.DateTime> EngDate { get; set; }
        public string NepaDate { get; set; }
        public string Bill_Ref { get; set; }
        public string Supplierid { get; set; }
        public Nullable<decimal> Previous_Bill { get; set; }
        public Nullable<decimal> today_Payment { get; set; }
        public Nullable<decimal> balanceNow { get; set; }
        public string Payment_Method { get; set; }
        public string Paymen_Given_By { get; set; }
        public string SystemUser { get; set; }
    }
}
