//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseReturn
    {
        public int Trano { get; set; }
        public string supplierid { get; set; }
        public string ReturnBillNo { get; set; }
        public string PurchaseRefNo { get; set; }
        public string itemNumber { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> QuantityReturn { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PreStock { get; set; }
        public Nullable<decimal> NewStock { get; set; }
        public string CauseForReturn { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> EngDate { get; set; }
        public string NepaDate { get; set; }
        public string systemUser { get; set; }
    }
}
