//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchsaeCode
    {
        public string Pruchase_Group { get; set; }
        public string PurchaseHeading { get; set; }
        public string PurchaseCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Alert { get; set; }
        public int TranNo { get; set; }
    }
}
