//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVoucher
    {
        public string Vn { get; set; }
        public Nullable<System.DateTime> Datefield { get; set; }
        public string MainAccHead { get; set; }
        public string AccountHead { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
        public string accountCode { get; set; }
    }
}
