//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegeGere
    {
        public int Tranno { get; set; }
        public string SchoolName { get; set; }
        public string RegistrationNo { get; set; }
        public string PANNo { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string SchoolType { get; set; }
        public string Country { get; set; }
        public string ContactPerson { get; set; }
        public string Cell_mobileContactPerson { get; set; }
        public string ComputerCode { get; set; }
        public string websie { get; set; }
        public string CodeSchool { get; set; }
    }
}
