//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remarksresultDivision
    {
        public int TranNo { get; set; }
        public string Division { get; set; }
        public Nullable<decimal> F_Percentage { get; set; }
        public Nullable<decimal> T_Percentage { get; set; }
        public string Remarks { get; set; }
        public string TeacherRemarks { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
