//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultIndivusalClassEntry
    {
        public string StudentId { get; set; }
        public string Name_field { get; set; }
        public string Class_Stu { get; set; }
        public string Sectionfield { get; set; }
        public string Roll_Stu { get; set; }
        public string TheoryMarks1 { get; set; }
        public string ParticalMarks1 { get; set; }
        public string TheoryMarks2 { get; set; }
        public string ParticalMarks2 { get; set; }
        public string TheoryMarks3 { get; set; }
        public string ParticalMarks3 { get; set; }
        public string TheoryMarks4 { get; set; }
        public string ParticalMarks4 { get; set; }
        public string TheoryMarks5 { get; set; }
        public string ParticalMarks5 { get; set; }
        public string TheoryMarks6 { get; set; }
        public string ParticalMarks6 { get; set; }
        public string TheoryMarks7 { get; set; }
        public string ParticalMarks7 { get; set; }
        public string TheoryMarks8 { get; set; }
        public string ParticalMarks8 { get; set; }
        public string TheoryMarks9 { get; set; }
        public string ParticalMarks9 { get; set; }
        public string TheoryMarks10 { get; set; }
        public string ParticalMarks10 { get; set; }
        public string TheoryMarks11 { get; set; }
        public string ParticalMarks11 { get; set; }
        public string TheoryMarks12 { get; set; }
        public string ParticalMarks12 { get; set; }
        public string TheoryMarks13 { get; set; }
        public string ParticalMarks13 { get; set; }
        public string TheoryMarks14 { get; set; }
        public string ParticalMarks14 { get; set; }
        public string TheoryMarks15 { get; set; }
        public string ParticalMarks15 { get; set; }
        public string TheoryMarks16 { get; set; }
        public string ParticalMarks16 { get; set; }
        public string TheoryMarks17 { get; set; }
        public string ParticalMarks17 { get; set; }
        public string TheoryMarks18 { get; set; }
        public string ParticalMarks18 { get; set; }
        public string TheoryMarks19 { get; set; }
        public string ParticalMarks19 { get; set; }
        public string TheoryMarks20 { get; set; }
        public string ParticalMarks20 { get; set; }
        public string PresentDay { get; set; }
        public string Writting { get; set; }
        public string Speaking { get; set; }
        public string Conduct { get; set; }
        public string Neatness { get; set; }
        public string Music_Dance { get; set; }
        public string Terms_Exan { get; set; }
        public string Year_exam { get; set; }
        public string Col1 { get; set; }
        public string Col2 { get; set; }
        public string Col3 { get; set; }
        public string Col4 { get; set; }
        public string Col5 { get; set; }
        public string Col6 { get; set; }
        public string Col7 { get; set; }
        public string Col8 { get; set; }
        public string Col9 { get; set; }
        public string Col10 { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
