//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class returnbook
    {
        public int TransNo { get; set; }
        public string studentId { get; set; }
        public string BooksCode { get; set; }
        public string Title { get; set; }
        public string AuthorsName { get; set; }
        public string Edition { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> Delayfine { get; set; }
        public Nullable<decimal> lostbooks { get; set; }
        public Nullable<decimal> BooksNotReturn { get; set; }
        public string Receiveby { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
