//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCode
    {
        public string SalesHeading { get; set; }
        public string SalesCode1 { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Standard_Unit { get; set; }
    }
}
