//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salestable
    {
        public int Sn { get; set; }
        public Nullable<System.DateTime> DateField { get; set; }
        public string SalesHeading { get; set; }
        public string PurchaseCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> NewStock { get; set; }
    }
}
