//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesprefix
    {
        public string Vn { get; set; }
        public Nullable<System.DateTime> Datefield { get; set; }
        public string Income { get; set; }
        public Nullable<decimal> IncomeMoney { get; set; }
    }
}
