//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesCash
    {
        public int tranNo { get; set; }
        public int InvoiceNo { get; set; }
        public string CustomerId { get; set; }
        public string CName { get; set; }
        public string Telephone { get; set; }
        public string PanVAt { get; set; }
        public string Addres { get; set; }
        public Nullable<System.DateTime> Datefiled { get; set; }
        public string NepaDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemDetail { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> PreStock { get; set; }
        public Nullable<decimal> StockBalance { get; set; }
        public string SystemUser { get; set; }
        public string TimeSales { get; set; }
        public string PaymentStatus { get; set; }
        public string ItemNumber { get; set; }
    }
}
