//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffsalaryformatGov
    {
        public string staff { get; set; }
        public string Staffname { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> SalaryScale { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> Gradeamount { get; set; }
        public Nullable<decimal> perincreament1 { get; set; }
        public Nullable<decimal> Total1 { get; set; }
        public Nullable<decimal> Reduceincrement { get; set; }
        public Nullable<decimal> Total2 { get; set; }
        public Nullable<decimal> Allowance1 { get; set; }
        public Nullable<decimal> SchoolAllowance { get; set; }
        public Nullable<decimal> Total3 { get; set; }
        public Nullable<decimal> Insurance { get; set; }
        public Nullable<decimal> Total4 { get; set; }
        public Nullable<decimal> taxamount { get; set; }
        public Nullable<decimal> Peski { get; set; }
        public Nullable<decimal> totalreduce { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public string other1 { get; set; }
        public string other2 { get; set; }
        public string other3 { get; set; }
        public string other4 { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
