//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffcasualleav
    {
        public int transno { get; set; }
        public string Stafid { get; set; }
        public Nullable<System.DateTime> Datevalue { get; set; }
        public Nullable<decimal> TotalAnualLeave { get; set; }
        public Nullable<decimal> TodayCasual { get; set; }
        public Nullable<decimal> remaincasual { get; set; }
        public string Remarks { get; set; }
        public string Approvedby { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
