//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentdiscountinformation
    {
        public int transno { get; set; }
        public string studentid { get; set; }
        public Nullable<System.DateTime> EnglishDate { get; set; }
        public string title_Heading { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
