//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentbooksInOut
    {
        public int tranNo { get; set; }
        public Nullable<System.DateTime> Date_English { get; set; }
        public string Miti { get; set; }
        public string Bookscode { get; set; }
        public Nullable<int> BooksTaken { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> bokestakendays { get; set; }
        public string RreturnMiti { get; set; }
        public Nullable<int> BooksReturn { get; set; }
        public string Remarks { get; set; }
        public string StudentId { get; set; }
        public Nullable<decimal> fines { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
