//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentmonthlybehavior
    {
        public int Tranno { get; set; }
        public string Studentid { get; set; }
        public string Namefield { get; set; }
        public string Class_stu { get; set; }
        public string YearValue { get; set; }
        public Nullable<System.DateTime> Datevalue { get; set; }
        public string Mistake1 { get; set; }
        public string Complainby { get; set; }
        public string MatterHandleby { get; set; }
        public string Desiciontaken { get; set; }
        public string Actiontaken { get; set; }
        public string CommetmentbyStudent { get; set; }
        public string Ramarks1 { get; set; }
        public string Ramarks2 { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
