//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentbillingsystem
    {
        public int transNo { get; set; }
        public string studentid { get; set; }
        public string studentName { get; set; }
        public string Stud_Class { get; set; }
        public string stud_roll { get; set; }
        public string stud_section { get; set; }
        public Nullable<System.DateTime> Englishdate { get; set; }
        public string nepalidate { get; set; }
        public string title_Heading { get; set; }
        public string paymentmonth { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
