//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subjectentrybyIndivusal
    {
        public int TranNo { get; set; }
        public string ExamTerms { get; set; }
        public string AcademicYear { get; set; }
        public string StudentId { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<decimal> Marks_Theory { get; set; }
        public Nullable<decimal> Marks_Partical { get; set; }
        public Nullable<int> Roll_Student { get; set; }
    }
}
