//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierList
    {
        public int SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string PanVat { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public string ResponsePerson { get; set; }
        public string Post { get; set; }
        public string Mobile { get; set; }
        public string GoodsType { get; set; }
        public string PaymentMode { get; set; }
        public string PayCondition { get; set; }
        public string NepaDate { get; set; }
    }
}
