//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSupplierBalance
    {
        public int TranNo { get; set; }
        public string Suppliercode { get; set; }
        public string CompanyNAme { get; set; }
        public string companyAddress { get; set; }
        public string Panvat { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
    }
}
