//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopMarksObtained
    {
        public int Tran { get; set; }
        public string Class_stu { get; set; }
        public Nullable<decimal> Subject1 { get; set; }
        public Nullable<decimal> Subject2 { get; set; }
        public Nullable<decimal> Subject3 { get; set; }
        public Nullable<decimal> Subject4 { get; set; }
        public Nullable<decimal> Subject5 { get; set; }
        public Nullable<decimal> Subject6 { get; set; }
        public Nullable<decimal> Subject7 { get; set; }
        public Nullable<decimal> Subject8 { get; set; }
        public Nullable<decimal> Subject9 { get; set; }
        public Nullable<decimal> Subject10 { get; set; }
        public Nullable<decimal> Subject11 { get; set; }
        public Nullable<decimal> Subject12 { get; set; }
        public Nullable<decimal> Subject13 { get; set; }
        public Nullable<decimal> Subject14 { get; set; }
        public Nullable<decimal> Subject15 { get; set; }
        public Nullable<decimal> Subject16 { get; set; }
        public Nullable<decimal> Subject17 { get; set; }
        public Nullable<decimal> Subject18 { get; set; }
        public Nullable<decimal> Subject19 { get; set; }
        public Nullable<decimal> Subject20 { get; set; }
        public string Examterm { get; set; }
        public string Year_B_C { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
