//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaraPabson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public string AccountID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<decimal> preBalanceAmount { get; set; }
        public Nullable<decimal> AmountDepositing { get; set; }
        public Nullable<decimal> AmountWithdrawl { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string currentuser { get; set; }
        public int TransNo { get; set; }
        public Nullable<int> Sc_1 { get; set; }
        public Nullable<int> Sc_2 { get; set; }
    }
}
